global:
  message: welcome to prod environment!
server:
  port: 8081
  message: hello from prod!
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cust_prod
    username: root
    password: 1080
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate,dialect.MySQL8Dialect
    open-in-view: false
    
