spring:
  application:
    name: customer-service
  datasource:
    url: jdbc:mysql://localhost:3306/cust_master
    driver-class-name: com.mysql.cj.jdbc.Drive
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    
